/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/gmilliez/robotpkg/localization/optitrack-genom3/work.elea/templates/ros/client/ros/optitrack/srv/abort_activity.srv
 *
 */


#ifndef OPTITRACK_MESSAGE_ABORT_ACTIVITY_H
#define OPTITRACK_MESSAGE_ABORT_ACTIVITY_H

#include <ros/service_traits.h>


#include <optitrack/abort_activityRequest.h>
#include <optitrack/abort_activityResponse.h>


namespace optitrack
{

struct abort_activity
{

typedef abort_activityRequest Request;
typedef abort_activityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct abort_activity
} // namespace optitrack


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::optitrack::abort_activity > {
  static const char* value()
  {
    return "f1ec71d84e024b77cbdc293016ea6480";
  }

  static const char* value(const ::optitrack::abort_activity&) { return value(); }
};

template<>
struct DataType< ::optitrack::abort_activity > {
  static const char* value()
  {
    return "optitrack/abort_activity";
  }

  static const char* value(const ::optitrack::abort_activity&) { return value(); }
};


// service_traits::MD5Sum< ::optitrack::abort_activityRequest> should match 
// service_traits::MD5Sum< ::optitrack::abort_activity > 
template<>
struct MD5Sum< ::optitrack::abort_activityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::optitrack::abort_activity >::value();
  }
  static const char* value(const ::optitrack::abort_activityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::optitrack::abort_activityRequest> should match 
// service_traits::DataType< ::optitrack::abort_activity > 
template<>
struct DataType< ::optitrack::abort_activityRequest>
{
  static const char* value()
  {
    return DataType< ::optitrack::abort_activity >::value();
  }
  static const char* value(const ::optitrack::abort_activityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::optitrack::abort_activityResponse> should match 
// service_traits::MD5Sum< ::optitrack::abort_activity > 
template<>
struct MD5Sum< ::optitrack::abort_activityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::optitrack::abort_activity >::value();
  }
  static const char* value(const ::optitrack::abort_activityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::optitrack::abort_activityResponse> should match 
// service_traits::DataType< ::optitrack::abort_activity > 
template<>
struct DataType< ::optitrack::abort_activityResponse>
{
  static const char* value()
  {
    return DataType< ::optitrack::abort_activity >::value();
  }
  static const char* value(const ::optitrack::abort_activityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPTITRACK_MESSAGE_ABORT_ACTIVITY_H
