/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/gmilliez/robotpkg/localization/optitrack-genom3/work.elea/templates/ros/client/ros/optitrack/srv/body_list.srv
 *
 */


#ifndef OPTITRACK_MESSAGE_BODY_LIST_H
#define OPTITRACK_MESSAGE_BODY_LIST_H

#include <ros/service_traits.h>


#include <optitrack/body_listRequest.h>
#include <optitrack/body_listResponse.h>


namespace optitrack
{

struct body_list
{

typedef body_listRequest Request;
typedef body_listResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct body_list
} // namespace optitrack


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::optitrack::body_list > {
  static const char* value()
  {
    return "328d12a893d6c58c991b1ed688d06b9d";
  }

  static const char* value(const ::optitrack::body_list&) { return value(); }
};

template<>
struct DataType< ::optitrack::body_list > {
  static const char* value()
  {
    return "optitrack/body_list";
  }

  static const char* value(const ::optitrack::body_list&) { return value(); }
};


// service_traits::MD5Sum< ::optitrack::body_listRequest> should match 
// service_traits::MD5Sum< ::optitrack::body_list > 
template<>
struct MD5Sum< ::optitrack::body_listRequest>
{
  static const char* value()
  {
    return MD5Sum< ::optitrack::body_list >::value();
  }
  static const char* value(const ::optitrack::body_listRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::optitrack::body_listRequest> should match 
// service_traits::DataType< ::optitrack::body_list > 
template<>
struct DataType< ::optitrack::body_listRequest>
{
  static const char* value()
  {
    return DataType< ::optitrack::body_list >::value();
  }
  static const char* value(const ::optitrack::body_listRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::optitrack::body_listResponse> should match 
// service_traits::MD5Sum< ::optitrack::body_list > 
template<>
struct MD5Sum< ::optitrack::body_listResponse>
{
  static const char* value()
  {
    return MD5Sum< ::optitrack::body_list >::value();
  }
  static const char* value(const ::optitrack::body_listResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::optitrack::body_listResponse> should match 
// service_traits::DataType< ::optitrack::body_list > 
template<>
struct DataType< ::optitrack::body_listResponse>
{
  static const char* value()
  {
    return DataType< ::optitrack::body_list >::value();
  }
  static const char* value(const ::optitrack::body_listResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPTITRACK_MESSAGE_BODY_LIST_H
