/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/gmilliez/robotpkg/localization/optitrack-genom3/work.elea/templates/ros/client/ros/optitrack/srv/connect_service.srv
 *
 */


#ifndef OPTITRACK_MESSAGE_CONNECT_SERVICE_H
#define OPTITRACK_MESSAGE_CONNECT_SERVICE_H

#include <ros/service_traits.h>


#include <optitrack/connect_serviceRequest.h>
#include <optitrack/connect_serviceResponse.h>


namespace optitrack
{

struct connect_service
{

typedef connect_serviceRequest Request;
typedef connect_serviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct connect_service
} // namespace optitrack


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::optitrack::connect_service > {
  static const char* value()
  {
    return "f373a4b174400403f47052cfc240215e";
  }

  static const char* value(const ::optitrack::connect_service&) { return value(); }
};

template<>
struct DataType< ::optitrack::connect_service > {
  static const char* value()
  {
    return "optitrack/connect_service";
  }

  static const char* value(const ::optitrack::connect_service&) { return value(); }
};


// service_traits::MD5Sum< ::optitrack::connect_serviceRequest> should match 
// service_traits::MD5Sum< ::optitrack::connect_service > 
template<>
struct MD5Sum< ::optitrack::connect_serviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::optitrack::connect_service >::value();
  }
  static const char* value(const ::optitrack::connect_serviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::optitrack::connect_serviceRequest> should match 
// service_traits::DataType< ::optitrack::connect_service > 
template<>
struct DataType< ::optitrack::connect_serviceRequest>
{
  static const char* value()
  {
    return DataType< ::optitrack::connect_service >::value();
  }
  static const char* value(const ::optitrack::connect_serviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::optitrack::connect_serviceResponse> should match 
// service_traits::MD5Sum< ::optitrack::connect_service > 
template<>
struct MD5Sum< ::optitrack::connect_serviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::optitrack::connect_service >::value();
  }
  static const char* value(const ::optitrack::connect_serviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::optitrack::connect_serviceResponse> should match 
// service_traits::DataType< ::optitrack::connect_service > 
template<>
struct DataType< ::optitrack::connect_serviceResponse>
{
  static const char* value()
  {
    return DataType< ::optitrack::connect_service >::value();
  }
  static const char* value(const ::optitrack::connect_serviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPTITRACK_MESSAGE_CONNECT_SERVICE_H
