/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/gmilliez/robotpkg/wip/optitrack-genom3/work.elea/templates/ros/client/ros/optitrack/msg/genom_state_component.msg
 *
 */


#ifndef OPTITRACK_MESSAGE_GENOM_STATE_COMPONENT_H
#define OPTITRACK_MESSAGE_GENOM_STATE_COMPONENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <optitrack/genom_state_task.h>
#include <optitrack/genom_state_activity.h>

namespace optitrack
{
template <class ContainerAllocator>
struct genom_state_component_
{
  typedef genom_state_component_<ContainerAllocator> Type;

  genom_state_component_()
    : task()
    , activity()
    , digest()
    , date()
    , version()  {
    }
  genom_state_component_(const ContainerAllocator& _alloc)
    : task(_alloc)
    , activity(_alloc)
    , digest(_alloc)
    , date(_alloc)
    , version(_alloc)  {
    }



   typedef std::vector< ::optitrack::genom_state_task_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::optitrack::genom_state_task_<ContainerAllocator> >::other >  _task_type;
  _task_type task;

   typedef std::vector< ::optitrack::genom_state_activity_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::optitrack::genom_state_activity_<ContainerAllocator> >::other >  _activity_type;
  _activity_type activity;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _digest_type;
  _digest_type digest;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _date_type;
  _date_type date;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _version_type;
  _version_type version;




  typedef boost::shared_ptr< ::optitrack::genom_state_component_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::optitrack::genom_state_component_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct genom_state_component_

typedef ::optitrack::genom_state_component_<std::allocator<void> > genom_state_component;

typedef boost::shared_ptr< ::optitrack::genom_state_component > genom_state_componentPtr;
typedef boost::shared_ptr< ::optitrack::genom_state_component const> genom_state_componentConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::optitrack::genom_state_component_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::optitrack::genom_state_component_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace optitrack

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/msg'], 'actionlib_msgs': ['/opt/ros/hydro/share/actionlib_msgs/msg'], 'optitrack': ['optitrack/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::optitrack::genom_state_component_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::optitrack::genom_state_component_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optitrack::genom_state_component_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optitrack::genom_state_component_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optitrack::genom_state_component_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optitrack::genom_state_component_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::optitrack::genom_state_component_<ContainerAllocator> >
{
  static const char* value()
  {
    return "91209663de20450ebde265fdddd8cdee";
  }

  static const char* value(const ::optitrack::genom_state_component_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x91209663de20450eULL;
  static const uint64_t static_value2 = 0xbde265fdddd8cdeeULL;
};

template<class ContainerAllocator>
struct DataType< ::optitrack::genom_state_component_<ContainerAllocator> >
{
  static const char* value()
  {
    return "optitrack/genom_state_component";
  }

  static const char* value(const ::optitrack::genom_state_component_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::optitrack::genom_state_component_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# IDL struct ::genom::state::component\n\
genom_state_task[] task\n\
genom_state_activity[] activity\n\
string digest\n\
string date\n\
string version\n\
\n\
================================================================================\n\
MSG: optitrack/genom_state_task\n\
# IDL struct ::genom::state::task\n\
string name\n\
genom_state_time cputime\n\
\n\
================================================================================\n\
MSG: optitrack/genom_state_time\n\
# IDL struct ::genom::state::time\n\
float64 last\n\
float64 max\n\
float64 avg\n\
\n\
================================================================================\n\
MSG: optitrack/genom_state_activity\n\
# IDL struct ::genom::state::activity\n\
uint16 id\n\
string name\n\
string state\n\
";
  }

  static const char* value(const ::optitrack::genom_state_component_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::optitrack::genom_state_component_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task);
      stream.next(m.activity);
      stream.next(m.digest);
      stream.next(m.date);
      stream.next(m.version);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct genom_state_component_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::optitrack::genom_state_component_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::optitrack::genom_state_component_<ContainerAllocator>& v)
  {
    s << indent << "task[]" << std::endl;
    for (size_t i = 0; i < v.task.size(); ++i)
    {
      s << indent << "  task[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::optitrack::genom_state_task_<ContainerAllocator> >::stream(s, indent + "    ", v.task[i]);
    }
    s << indent << "activity[]" << std::endl;
    for (size_t i = 0; i < v.activity.size(); ++i)
    {
      s << indent << "  activity[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::optitrack::genom_state_activity_<ContainerAllocator> >::stream(s, indent + "    ", v.activity[i]);
    }
    s << indent << "digest: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.digest);
    s << indent << "date: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.date);
    s << indent << "version: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.version);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPTITRACK_MESSAGE_GENOM_STATE_COMPONENT_H
