/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/gmilliez/robotpkg/wip/optitrack-genom3/work.elea/templates/ros/client/ros/optitrack/msg/or_t3d_acc_cov.msg
 *
 */


#ifndef OPTITRACK_MESSAGE_OR_T3D_ACC_COV_H
#define OPTITRACK_MESSAGE_OR_T3D_ACC_COV_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace optitrack
{
template <class ContainerAllocator>
struct or_t3d_acc_cov_
{
  typedef or_t3d_acc_cov_<ContainerAllocator> Type;

  or_t3d_acc_cov_()
    : cov()  {
      cov.assign(0.0);
  }
  or_t3d_acc_cov_(const ContainerAllocator& _alloc)
    : cov()  {
      cov.assign(0.0);
  }



   typedef boost::array<double, 6>  _cov_type;
  _cov_type cov;




  typedef boost::shared_ptr< ::optitrack::or_t3d_acc_cov_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::optitrack::or_t3d_acc_cov_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct or_t3d_acc_cov_

typedef ::optitrack::or_t3d_acc_cov_<std::allocator<void> > or_t3d_acc_cov;

typedef boost::shared_ptr< ::optitrack::or_t3d_acc_cov > or_t3d_acc_covPtr;
typedef boost::shared_ptr< ::optitrack::or_t3d_acc_cov const> or_t3d_acc_covConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::optitrack::or_t3d_acc_cov_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::optitrack::or_t3d_acc_cov_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace optitrack

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/msg'], 'actionlib_msgs': ['/opt/ros/hydro/share/actionlib_msgs/msg'], 'optitrack': ['optitrack/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::optitrack::or_t3d_acc_cov_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::optitrack::or_t3d_acc_cov_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optitrack::or_t3d_acc_cov_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optitrack::or_t3d_acc_cov_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optitrack::or_t3d_acc_cov_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optitrack::or_t3d_acc_cov_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::optitrack::or_t3d_acc_cov_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2fbfb35bde7544ba5714eacec63a8224";
  }

  static const char* value(const ::optitrack::or_t3d_acc_cov_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2fbfb35bde7544baULL;
  static const uint64_t static_value2 = 0x5714eacec63a8224ULL;
};

template<class ContainerAllocator>
struct DataType< ::optitrack::or_t3d_acc_cov_<ContainerAllocator> >
{
  static const char* value()
  {
    return "optitrack/or_t3d_acc_cov";
  }

  static const char* value(const ::optitrack::or_t3d_acc_cov_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::optitrack::or_t3d_acc_cov_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# IDL struct ::or::t3d::acc_cov\n\
float64[6] cov\n\
";
  }

  static const char* value(const ::optitrack::or_t3d_acc_cov_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::optitrack::or_t3d_acc_cov_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cov);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct or_t3d_acc_cov_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::optitrack::or_t3d_acc_cov_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::optitrack::or_t3d_acc_cov_<ContainerAllocator>& v)
  {
    s << indent << "cov[]" << std::endl;
    for (size_t i = 0; i < v.cov.size(); ++i)
    {
      s << indent << "  cov[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.cov[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPTITRACK_MESSAGE_OR_T3D_ACC_COV_H
