# IDL enum ::niut::JOINT
uint32 niut_ZERO = 0
uint32 niut_HEAD = 1
uint32 niut_NECK = 2
uint32 niut_TORSO = 3
uint32 niut_WAIST = 4
uint32 niut_LEFT_COLLAR = 5
uint32 niut_LEFT_SHOULDER = 6
uint32 niut_LEFT_ELBOW = 7
uint32 niut_LEFT_WRIST = 8
uint32 niut_LEFT_HAND = 9
uint32 niut_LEFT_FINGERTIP = 10
uint32 niut_RIGHT_COLLAR = 11
uint32 niut_RIGHT_SHOULDER = 12
uint32 niut_RIGHT_ELBOW = 13
uint32 niut_RIGHT_WRIST = 14
uint32 niut_RIGHT_HAND = 15
uint32 niut_RIGHT_FINGERTIP = 16
uint32 niut_LEFT_HIP = 17
uint32 niut_LEFT_KNEE = 18
uint32 niut_LEFT_ANKLE = 19
uint32 niut_LEFT_FOOT = 20
uint32 niut_RIGHT_HIP = 21
uint32 niut_RIGHT_KNEE = 22
uint32 niut_RIGHT_ANKLE = 23
uint32 niut_RIGHT_FOOT = 24

uint32 value
