bool morseHuman
bool niutHuman
bool groupHuman
bool mocapHuman
bool adreamMocapHuman
bool toasterSimuHuman
bool pr2Robot
bool spencerRobot
bool toasterSimuRobot
bool toasterSimuObject
bool arObject
bool om2mObject
bool gazeboObject
---
