uint32 pointingAgentId
string pointingAgentName
string pointingJoint
float64 pointingJointDistThreshold
float64 angleThreshold
---
bool answer
uint32[] pointedId
float64[] confidence
string[] pointedName